name: Release

on:
  release:
    types: [created, edited]

jobs:
  releases-matrix:
    name: Release shopify-extensions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: linux/386, linux/amd64, windows/386, windows/amd64, darwin/amd64, darwin/arm64
        goos: [linux, windows, darwin]
        goarch: ["386", amd64]
        exclude:
          - goarch: "386"
            goos: darwin
        include:
          - goos: darwin
            goarch: arm64

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup build toolchain
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Build and package executable
        run: GOOS=${{ matrix.goos}} GOARCH=${{ matrix.goarch }} make package
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: shopify-extensions-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz
          tag: ${{ github.ref }}
